try foo() { x: 1 } {
} catch {
}
